### ISSUE TITLE
Práctica 6

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/practica-de-hilos-bg55-a#2]
[practica 6 Hilos en consola.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-bg55-a/files/8439522/practica.6.Hilos.en.consola.pdf)

**Comment by EvelynLopezz** [comment]
Calificación de la práctica de Adolfo German Vásquez Rojas:
16.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
